// File generated by FlutterFire CLI.
// User must run `flutterfire configure` to populate this properly.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured. '
      'Please run `flutterfire configure` in your terminal to generate this file.',
    );
  }
}
